version: '3.8'
services:
  front-end:
        container_name: front-end
        build:
          context: ./frontend-web/fullstackjavapxl
          dockerfile: Dockerfile
        ports:      
          - "9000:80"
